API_KEY = "VHolTCKfT5aDvMVvil8skbLjh09ddGdSxQpe1M9X1fQT0SQVgnGXGfkhLNfHHIzl"
API_SECRET = "3zcIslaGZkXkE7B7IzxdF1HCgIQFfpGQc1B8p4vVbBrovjBHQl0LVESoKWLjCsiZ"

EXCHANGE_NAME = "binance"

TRADE_AMOUNT = 1
FEE_RATE = 0.001

MIN_PROFIT = 0.005

AUTO_TRADE = True